export const MODALIZE_HEADER_TYPE = {
  CUSTOM: 0,
  TITLE_TEXT: 1,
  SINGLE_BUTTON: 2,
};

export const MODALIZE_FOOTER_TYPE = {
  CUSTOM: 0,
  BUTTON_EDIT_DELETE: 1,
  DOUBLE_BUTTON: 2,
  SINGLE_BUTTON: 3,
  LOADING: 4,
  SUCESS_ALERT: 5,
  ERROR_ALERT: 6,
  ALERT_EMPTY_FLATLIST: 7,
};
