// const FONTS = {
//   Poppins_Black: 'Poppins-Black',
//   Poppins_Black_Italic: 'Poppins-BlackItalic',
//   Poppins_Bold: 'Poppins-Bold',
//   Poppins_BoldItalic: 'Poppins-BoldItalic',
//   Poppins_ExtraBold: 'Poppins-ExtraBold',
//   Poppins_ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
//   Poppins_ExtraLight: 'Poppins-ExtraLight',
//   Poppins_ExtraLightItalic: 'Poppins-ExtraLightItalic',
//   Poppins_Italic: 'Poppins-Italic',
//   Poppins_Light: 'Poppins-Light',
//   Poppins_LightItalic: 'Poppins-LightItalic',
//   Poppins_Medium: 'Poppins-Medium',
//   Poppins_MediumItalic: 'Poppins-MediumItalic',
//   Poppins_Regular: 'Poppins-Regular',
//   Poppins_SemiBold: 'Poppins-SemiBold',
//   Poppins_SemiBoldItalic: 'Poppins-SemiBoldItalic',
//   Poppins_Thin: 'Thin',
//   Poppins_ThinItalic: 'ThinItalic',
// };
// export { FONTS };

const FONTS = {
  FonteProLight: 'Cocogoose Pro Light-trial',
  FonteProSemi: 'Cocogoose Pro Semilight-trial',
  FonteProThin: 'Montserrat-Thin',
  FonteProUltra: 'Cocogoose Pro Ultralight-trial',
  FonteProTrial: 'Montserrat-Black',
  FonteProItalicTrial: 'Cocogoose Pro Italic-trial',

  Montserrat_Black: 'Montserrat-Black',
  Montserrat_BlackItalic: 'Montserrat-BlackItalic',
  Montserrat_Bold: 'Montserrat-Bold',
  Montserrat_BoldItalic: 'Montserrat-BoldItalic',
  Montserrat_ExtraBold: 'Montserrat-ExtraBold',
  Montserrat_ExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
  Montserrat_ExtraLight: 'Montserrat-ExtraLight',
  Montserrat_Italic: 'Montserrat-Italic',
  Montserrat_Thin: 'Montserrat-Thin',
  Montserrat_Light: 'Montserrat-Light',
  Montserrat_Medium: 'Montserrat-Medium',

  Poppins_Black: 'Poppins-Black',
  Poppins_Black_Italic: 'Poppins-BlackItalic',
  Poppins_Bold: 'Poppins-Bold',
  Poppins_BoldItalic: 'Poppins-BoldItalic',
  Poppins_ExtraBold: 'Poppins-ExtraBold',
  Poppins_ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  Poppins_ExtraLight: 'Poppins-ExtraLight',
  Poppins_ExtraLightItalic: 'Poppins-ExtraLightItalic',
  Poppins_Italic: 'Poppins-Italic',
  Poppins_Light: 'Poppins-Light',
  Poppins_LightItalic: 'Poppins-LightItalic',
  Poppins_Medium: 'Poppins-Medium',
  Poppins_MediumItalic: 'Poppins-MediumItalic',
  Poppins_Regular: 'Poppins-Regular',
  Poppins_SemiBold: 'Poppins-SemiBold',
  Poppins_SemiBoldItalic: 'Poppins-SemiBoldItalic',
  Poppins_Thin: 'Thin',
  Poppins_ThinItalic: 'ThinItalic',
};
export { FONTS };
